services:
  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    ports:               # ← change here
      - "5300:5300"
    networks:
      - app-network

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    ports:
      - "5050:5050"
    networks:
      - app-network

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_DATABASE=mlagrp6db
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
    ports:
      - "8080:8080"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-north-1"        # change to your region
        awslogs-group: "authservice-logs"
        awslogs-stream: "authservice"
        awslogs-create-group: "true"

    networks:
      - app-network

  workout-api:
    build:
      context: ./workout-api
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8000:8000"
    networks:
      - app-network

  nutrition-api:
    build: ./nutrition-api
    environment:
      - MONGO_URI=${MONGO_URI}
    expose:
      - "5005"
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - app-network

  # loki:
  #   image: grafana/loki:2.9.0
  #   ports:
  #     - "3100:3100"

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - app-network
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:10.3.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
