events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://authservice:8080/;
        }

        location /activity/ {
            proxy_pass http://activity-tracking:5300/;
        }

        location /workout/ {
            proxy_pass http://workout-api:8000/;
        }

        location /group/ {
            proxy_pass http://group-api:8005/;
        }

        location /nutrition/ {
            proxy_pass http://nutrition-api:5005/;
        }

        location /analytics/ {
            proxy_pass http://analytics:5050/;
        }

        # Optional: handle websockets for real-time services
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}