# App logs
logging.level.com.authservice=DEBUG

# Spring (keep noise low)
logging.level.org.springframework=INFO

# 🔒 Sensitive data protection
logging.level.org.springframework.web.method.annotation.RequestResponseBodyMethodProcessor=WARN
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN
logging.level.org.springframework.data.mongodb.repository.query.MongoQueryCreator=WARN

# spring.data.mongodb.database=test
# spring.data.mongodb.uri=mongodb://root:cfgmla23@localhost:27017
spring.data.mongodb.uri=mongodb+srv://mlagroup6_db_user1:Mlagrp6%402026@mlagroup6datacluster.ms0cuuq.mongodb.net/mlagrp6db
spring.data.mongodb.database=mlagrp6db


# SMTP server settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# spring.mail.username=haritha22081117@gmail.com
# spring.mail.password=ckmp mfok guxm oaep
spring.mail.username=mla.fitness.group6@gmail.com
spring.mail.password=fabp cnvd jlfn wucq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Optional
spring.mail.default-encoding=UTF-8

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs

